name: dart_voip
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  flutter_webrtc: ^1.0.0
  provider: ^6.1.5


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
